name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=frontend/dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Koyeb CLI
        run: |
          curl -sL https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb-cli_linux_amd64.tar.gz | tar xz
          sudo mv koyeb-cli /usr/local/bin/koyeb

      - name: Deploy to Koyeb
        run: koyeb service deploy -f koyeb.yaml
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
